#!/bin/bash

GREP_FLAGS=""
SED_FLAGS=""
if [ "$(uname)" == "Darwin" ]; then
    GREP_FLAGS="-E"
    SED_FLAGS="-i \'\'"
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    GREP_FLAGS="-P"
    SED_FLAGS="-i"
fi

DIR=$1
OUTFILE=$2

if [ "${OUTFILE}" == "" ]; then
    OUTFILE="header_out.hpp"
fi

FILES=$(find ${DIR} -print | grep ${GREP_FLAGS}o '.+(\.hpp|\.cpp|\.h|\.cc|\.c)$')
ALL_DEP=$(echo "${FILES}" | grep ${GREP_FLAGS}o '[^\/]+\.\w+(\s+|$)' | sed 's/\./\\\./g')

DONE=0
PASS_NUM=0

while [ ${DONE} == 0 ]; do
    echo "PASS ${PASS_NUM}"

    FILE_NAMES=$(echo "${FILES}" | grep ${GREP_FLAGS}o '[^\/]+\.\w+(\s+|$)') 
    NEXT_FILES=""

    for FILE in ${FILES}; do
        echo "Checking ${FILE}"
        DEP=0
        for DEPENDENCY in ${FILE_NAMES}; do
            ESCAPED=$(echo ${DEPENDENCY} | sed 's/\./\\\./g')
            if [ "$(grep ${GREP_FLAGS} "\#include (\<|\")${ESCAPED}(\>|\")" ${FILE})" != "" ]; then
                echo "depends on ${DEPENDENCY}"
                DEP=1
            fi
        done
        if [ ${DEP} == 0 ]; then
            echo "APPENDING FILE ${FILE}"
            cat ${FILE} >> ${OUTFILE}
        else 
            NEXT_FILES="${NEXT_FILES} ${FILE}"
        fi
    done
    
    if [ "${FILES}" == "" ]; then
        DONE=1
    else
        FILES=${NEXT_FILES}
        PASS_NUM=$((${PASS_NUM} + 1))
    fi
done

echo "${ALL_DEP}"

for DEP in ${ALL_DEP}; do
    sed -E ${SED_FLAGS} "/\#include (\<|\")${DEP}(\>|\")/d" ${OUTFILE}
done
